# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7d61b7aac4859f4d2c86f6acc3e96ae931d959772157af56f593ce4b1551956fdfc799116ddf1ffb82366a3842179a55c174187e5b6acc5eda4b47d96ca2c9f9

test:
  secret_key_base: b4b6b9a2edea88a310aedc6d4f237e8fdee57471862f1de13b058764f5cd0125e732881e50fe862bd6342b62207590df4d0e2b621f34fb81942018ca4da20bec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
